### ISSUE TITLE
CodeSanity installation script fails due to not updating scan_combo.target

### ISSUE THREAD

**Issue by kfrencher** [saschawildgrube/servicenow-codesanity#20]
I'm running Tokyo on a PDI instance installing CodeSanity. I've already installed DevTools. Below is my instance details:

> Build name: Tokyo
> Build date: 09-16-2022_1610
> Build tag: glide-tokyo-07-08-2022__patch1-09-01-2022

I see the following output after running the installation script indicating that the installation failed because it couldn't update a sys_dictionary record.

> CodeSanity: Installation BEGIN
> Creating a new choice "CodeSanity" for scan_check category.: Record has been created.
> Setting the scan timeout to 6 hours: Set record sysrule_quota: 139d8c680f1333006e5140c1df767e86 value "max_duration" to: 21600
> ERROR: Setting the column scan_combo.target no_truncate attribute: Failed to set record sys_dictionary:505bfabb1bd201103297fd9b8b4bcb87 value "attributes" to: no_sort=true,slushbucket_ref_no_expand=true,no_truncate=true
> CodeSanity: Installation FAILED

I looked in my instance and that record does not exist. There is a record for scan_combo.targets with sys_id 90818e8c75a401100acb0f6766fcbfba. I'm assuming that's what should be updated.

**Comment by saschawildgrube** [comment]
hey there. yes, that's a known issue in version 2.7.0 and already fixed in the dev branch (2.8.0 is to be released soon).
The change is "just" cosmetic, so you can ignore it.
The sys_dictionary records of fields indeed have different sys_id in different family releases - but not on upgrades instances. Tricky.
However, it shows that I should even more submit to my own checks - and not use sys_ids in code ;)
